// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qusephrgntdztzdqfmzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1c2VwaHJnbnRkenR6ZHFmbXppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxODQ2NjAsImV4cCI6MjA3MDc2MDY2MH0.TI3sy3RKQCpxn3DeRqKD-JRAtcsRPZznZdztk6oZmzw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});